---
title: "Target Markdown"
output: html_document
---


# Set up targets environment

Here we run necessary code for `targets` setup.

```{r setup, include = FALSE}
here::set_here()
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")

# load libraries for targets notebook
library(targets)
library(dplyr, quietly = TRUE)

# clean knitting history
tar_unscript()
```

# Dependencies

Here, we load packages and custom functions required in the pipeline.

```{targets example-globals, tar_globals = TRUE}
options(tidyverse.quiet = TRUE)

# load libraries for make
tar_option_set(packages = c("dplyr",
                            "tidyr",
                            "purrr",
                            "readr",
                            "quanteda",
                            "igraph",
                            "DiagrammeR"
                            ))

# read custom functions
lapply(list.files(here::here("R"), full.names = TRUE), source)
```

# Data import


```{targets one_author}
list(
    
    tar_target(one_author,
               read.csv2(here::here("data", "raw", "Binter_pubs.csv")),
               format = "qs"
)
    
)
```


# Edgelist

```{targets edgelist}

list(
    
    tar_target(edgelist,
               make_edgelist(one_author))
    
)

```

# Check results

```{r}

```

etc... rinse and repeat